package com.example.demo.model;

public class Emp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.empno
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	private Integer empno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.ename
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	private String ename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.job
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.sal
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	private Double sal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.empno
	 * @return  the value of emp.empno
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public Integer getEmpno() {
		return empno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.empno
	 * @param empno  the value for emp.empno
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public void setEmpno(Integer empno) {
		this.empno = empno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.ename
	 * @return  the value of emp.ename
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public String getEname() {
		return ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.ename
	 * @param ename  the value for emp.ename
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public void setEname(String ename) {
		this.ename = ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.job
	 * @return  the value of emp.job
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.job
	 * @param job  the value for emp.job
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.sal
	 * @return  the value of emp.sal
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public Double getSal() {
		return sal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.sal
	 * @param sal  the value for emp.sal
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	public void setSal(Double sal) {
		this.sal = sal;
	}
}