package com.example.demo.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.empno
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ename
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.job
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sal
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    private Double sal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.empno
     *
     * @return the value of member.empno
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.empno
     *
     * @param empno the value for member.empno
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ename
     *
     * @return the value of member.ename
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ename
     *
     * @param ename the value for member.ename
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.job
     *
     * @return the value of member.job
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.job
     *
     * @param job the value for member.job
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sal
     *
     * @return the value of member.sal
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public Double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sal
     *
     * @param sal the value for member.sal
     *
     * @mbg.generated Thu Nov 15 15:24:21 KST 2018
     */
    public void setSal(Double sal) {
        this.sal = sal;
    }
}