package com.example.demo.mapper;

import com.example.demo.model.Emp;
import com.example.demo.model.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	long countByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int deleteByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int deleteByPrimaryKey(Integer empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int insert(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int insertSelective(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	List<Emp> selectByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	Emp selectByPrimaryKey(Integer empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int updateByPrimaryKeySelective(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbg.generated  Thu Nov 15 15:24:21 KST 2018
	 */
	int updateByPrimaryKey(Emp record);
}